/** @const {ShadowJS} */ var Notification;
/** @const {ShadowJS} */ var Promise;
/** @const {ShadowJS} */ var alert;
/** @const {ShadowJS} */ var clearInterval;
/** @const {ShadowJS} */ var confirm;
/** @const {ShadowJS} */ var fetch;
/** @const {ShadowJS} */ var module;
/** @const {ShadowJS} */ var prompt;
/** @const {ShadowJS} */ var setInterval;
ShadowJS.prototype.Children.toArray;
ShadowJS.prototype.Component;
ShadowJS.prototype.Fragment;
ShadowJS.prototype._handle_change;
ShadowJS.prototype._peek;
ShadowJS.prototype._peek_at;
ShadowJS.prototype._queued_run;
ShadowJS.prototype._run;
ShadowJS.prototype._set_opts;
ShadowJS.prototype._set_state;
ShadowJS.prototype._try_capture;
ShadowJS.prototype._update_watching;
ShadowJS.prototype.add_after_render;
ShadowJS.prototype.add_before_flush;
ShadowJS.prototype.cljsIsDirty;
ShadowJS.prototype.createElement;
ShadowJS.prototype.defineProperty;
ShadowJS.prototype.existsSync;
ShadowJS.prototype.floor;
ShadowJS.prototype.flush_after_render;
ShadowJS.prototype.flush_before_flush;
ShadowJS.prototype.flush_queues;
ShadowJS.prototype.flush_render;
ShadowJS.prototype.forceUpdate;
ShadowJS.prototype.memo;
ShadowJS.prototype.mkdirSync;
ShadowJS.prototype.onChange;
ShadowJS.prototype.parse;
ShadowJS.prototype.props;
ShadowJS.prototype.queue_render;
ShadowJS.prototype.readFileSync;
ShadowJS.prototype.ref;
ShadowJS.prototype.reject;
ShadowJS.prototype.render;
ShadowJS.prototype.resolve;
ShadowJS.prototype.run_queues;
ShadowJS.prototype.schedule;
ShadowJS.prototype.stringify;
ShadowJS.prototype.useEffect;
ShadowJS.prototype.useRef;
ShadowJS.prototype.useState;
ShadowJS.prototype.writeFileSync;